trigger:
  - main

resources:
  repositories:
    - repository: self

variables:
  dockerRegistryServiceConnection: 'shdcrbdppe1eus2cr'
  tag: '$(Build.BuildId)'
  configMap: my-config
  vmImageName: ubuntu-20.04


stages:
  # - stage: CI
  #   pool:
  #     vmImage: $(vmImageName)
  #   jobs:
  - stage: CD
    displayName: CD

    pool:
      vmImage: $(vmImageName)

    jobs:
    - job: CI
      steps:
      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            env | sort
            pwd
            ls -alt
      - publish:  $(System.DefaultWorkingDirectory)
        artifact: allfiles

    - deployment: Deploy
      dependsOn: Ci
      displayName: Deploy
      environment: 'scicoriabd.development'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: Bash@3
                inputs:
                  targetType: inline
                  script: |
                    env | sort
                    pwd
                    ls -alt $(Pipeline.Workspace)
                    aikey=$(yq e '.azure.application-insights.instrumentation-key' $(Pipeline.Workspace)/allfiles/app.yml)
                    echo $aikey
                    echo "set the value"
                    echo "##vso[task.setvariable variable=AI_KEY]InstrumentationKey=$aikey"

              - task: Kubernetes@1
                displayName: 'Create ConfigMap'
                inputs:
                  connectionType: Kubernetes Service Connection
                  kubernetesServiceEndpoint: scicoriabd-scicoriabd-development-1627985149772
                  namespace: development
                  forceUpdateConfigMap: true
                  configMapName: $(configMap)
                  configMapArguments: >
                    --from-file=$(Pipeline.Workspace)/allfiles/game.properties
                    --from-file=application-yml=$(Pipeline.Workspace)/allfiles/app.yml
                    --from-literal=azure.application-insights.instrumentation-key=$(AI_KEY)
              - task: KubernetesManifest@0
                displayName: Deploy to Kubernetes cluster
                inputs:
                  action: deploy
                  manifests: $(Pipeline.Workspace)/allfiles/deployment.yaml

