trigger:
  - main

variables:
  dockerRegistryServiceConnection: 'shdcrbdppe1eus2cr'
  tag: '$(Build.BuildId)'
  configMap: my-config
  vmImageName: ubuntu-20.04


stages:
  - stage: CD
    displayName: CD

    pool:
      vmImage: $(vmImageName)

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: 'scicoriabd.development'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: Bash@3
                inputs:
                  targetType: inline
                  script: |
                    env | sort
                    pwd
                    ls -alt
              - task: Kubernetes@1
                displayName: 'Create ConfigMap'
                inputs:
                  connectionType: Kubernetes Service Connection
                  kubernetesServiceEndpoint: scicoriabd-scicoriabd-development-1627985149772
                  namespace: development
                  forceUpdateConfigMap: true
                  configMapName: $(configMap)
                  configMapArguments: >
                    --from-file=$(Pipeline.Workspace)/game.properties
                  #  --from-literal=azure.application-insights.instrumentation-key=$(yq e '.azure.application-insights.instrumentation-key' $(Pipeline.Workspace)/app.yml)
                  #  --from-file=application.yml=$(Pipeline.Workspace)/app.yml


              - task: KubernetesManifest@0
                displayName: Deploy to Kubernetes cluster
                inputs:
                  action: deploy
                  manifests: $(Pipeline.Workspace)/deployment.yaml

